name: Deploy

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Check for TypeScript errors
        run: yarn tsc

      - name: Check for style violations
        run: yarn prettier -c src/

  deploy:
      name: Deploy
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/main'
      needs: test

      steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install --prod

      - name: Set Version
        run: echo "" >> wrangler.toml; echo "VERSION = \"$(git rev-parse --short HEAD)\"" >> wrangler.toml

      - name: Deploy to Cloudflare Workers with Wrangler
        with:
            apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        uses: cloudflare/wrangler-action@3.3.2
